### ISSUE TITLE
Is there any way to load more media?

### ISSUE THREAD

**Issue by lmanzurv** [mishbahr/djangocms-instagram#4]
I am using the plugin and set the count of media to 9, but I would like to include a load more button that allows me to load more media in the same amount (the first time would fetch from 10 to 18, the second from 19 to 27, and so on).

Is there any way to do this with the current code?

**Comment by mishbahr** [comment]
Hey @lmanzurv .. unfortunately that's not possible with the current code base.

**Comment by mishbahr** [comment]
Closing this, not really an issue. 

Feel free to do a pull request, if you implement this feature.
